# Generated by Django 5.1.3 on 2024-11-11 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='content',
            new_name='text',
        ),
    ]
